### PR TITLE
scripts to clone all synApps modules from GitHub

### LINKED ISSUE #1: create a script to clone synApps from GitHub
similar to checkout.sh

### PR DESCRIPTION
**Pull request by prjemian**
Windows batch file tested OK, fixes #1

### CODE REVIEW

**Comment by prjemian** [comment]
BTW, script was developed & tested on RHEL6 linux

**Comment by prjemian** [comment]
@MarkRivers : can you check this works for you on Windows?
@timmmooney : can you check this works for you on linux?

If so, this can merge.

**Comment by MarkRivers** [comment]
I don't actually run git or svn on Window.  My working directories are on Linux, and I use samba to mount the Linux file system from Windows.

**Comment by prjemian** [comment]
Ok.

**Comment by timmmooney** [comment]
It works for me.

**Pull request merged**
